# Generated by Django 3.2.9 on 2022-01-18 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 18, 19, 39, 25, 298166)),
            preserve_default=False,
        ),
    ]
