# Generated by Django 3.2.9 on 2022-01-23 19:14

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_comment_uploaded_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos', validators=[home.models.validate_image]),
        ),
    ]
