# Generated by Django 3.2.9 on 2022-01-23 19:17

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_post_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilephoto',
            field=models.ImageField(blank=True, null=True, upload_to='profilepicture', validators=[home.models.validate_image]),
        ),
    ]
