# Generated by Django 3.2.9 on 2022-01-24 17:55

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_profile_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilephoto',
            field=models.FileField(blank=True, null=True, upload_to='profilepicture', validators=[home.models.validate_image]),
        ),
    ]
