# Generated by Django 3.2.9 on 2022-01-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_post_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
