# Generated by Django 3.2.9 on 2022-01-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_post_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
