# Generated by Django 3.2.9 on 2022-01-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20220126_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unique',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
