# Generated by Django 3.2.9 on 2022-01-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_chatbackground_privateaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privatefollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(max_length=100)),
                ('requesting', models.CharField(max_length=100)),
            ],
        ),
    ]
