# Generated by Django 3.2.9 on 2022-01-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_privatefollow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporarynotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('chat_photos', models.TextField(blank=True, max_length=1000, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
