# Generated by Django 3.2.9 on 2022-01-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_temporarynotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatblock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_user', models.CharField(max_length=100)),
                ('blocked_by', models.CharField(max_length=100)),
            ],
        ),
    ]
