# Generated by Django 3.2.9 on 2022-01-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='username',
            new_name='liked_by',
        ),
    ]
