# Generated by Django 3.2.9 on 2022-01-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_username_likes_liked_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likefollowcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('liked_by', models.CharField(max_length=100)),
                ('commented_by', models.CharField(max_length=100)),
                ('following', models.CharField(max_length=100)),
            ],
        ),
    ]
