# Generated by Django 3.2.9 on 2022-01-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_likefollowcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likefollowcomment',
            new_name='Likefollowcommentnoti',
        ),
    ]
