# Generated by Django 3.2.9 on 2022-01-30 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_likefollowcomment_likefollowcommentnoti'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likefollowcommentnoti',
            old_name='following',
            new_name='followed_by',
        ),
    ]
