# Generated by Django 3.2.9 on 2022-01-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_following_likefollowcommentnoti_followed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likefollowcommentnoti',
            name='commented_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='likefollowcommentnoti',
            name='followed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='likefollowcommentnoti',
            name='liked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='likefollowcommentnoti',
            name='postid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='likefollowcommentnoti',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
