# Generated by Django 3.2.9 on 2022-01-30 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_likefollowcommentnoti_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='likefollowcommentnoti',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 30, 23, 17, 55, 335428)),
            preserve_default=False,
        ),
    ]
