# Generated by Django 3.2.9 on 2022-01-31 19:35

import cloudinary_storage.storage
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_likefollowcommentnoti_uploaded_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactdeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('issue', models.TextField(blank=True, max_length=1000, null=True)),
                ('photos', models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='contactdeveloper', validators=[home.models.validate_image])),
            ],
        ),
    ]
