# Generated by Django 3.2.9 on 2022-01-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_contactdeveloper'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdeveloper',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactdeveloper',
            name='issue',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactdeveloper',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactdeveloper',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
