# Generated by Django 3.2.9 on 2022-02-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_verifiedaccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creategroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='', max_length=100)),
                ('group_description', models.CharField(default='', max_length=1000)),
                ('created_by', models.CharField(default='', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
