# Generated by Django 3.2.9 on 2022-02-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_creategroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouppeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('group_name', models.CharField(default='', max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
