# Generated by Django 3.2.9 on 2022-02-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_grouppeople'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouppeople',
            old_name='sent_on',
            new_name='added_on',
        ),
        migrations.RemoveField(
            model_name='grouppeople',
            name='message',
        ),
        migrations.RemoveField(
            model_name='grouppeople',
            name='sender',
        ),
    ]
