# Generated by Django 3.2.9 on 2022-02-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20220218_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppeople',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
