# Generated by Django 3.2.9 on 2022-02-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_groupsendmessages_sent_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppeople',
            name='group_name',
        ),
    ]
