# Generated by Django 3.2.9 on 2022-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_grouppeople_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppeople',
            name='group_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
