# Generated by Django 3.2.9 on 2022-02-18 18:53

import cloudinary_storage.storage
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_grouppeople_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='creategroup',
            name='group_photo',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage, upload_to='group_photo', validators=[home.models.validate_image]),
        ),
    ]
