# Generated by Django 3.2.9 on 2022-02-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_creategroup_group_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsendmessages',
            name='added_left',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
